Document: fileaccessmonitor
Title: Debian fileaccessmonitor Manual
Author: <insert document author here>
Abstract: This manual describes what fileaccessmonitor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fileaccessmonitor/fileaccessmonitor.sgml.gz

Format: postscript
Files: /usr/share/doc/fileaccessmonitor/fileaccessmonitor.ps.gz

Format: text
Files: /usr/share/doc/fileaccessmonitor/fileaccessmonitor.text.gz

Format: HTML
Index: /usr/share/doc/fileaccessmonitor/html/index.html
Files: /usr/share/doc/fileaccessmonitor/html/*.html
